"""Host process for the Visio->ArchiMate workflow — one Python host per business process
(the Azure Container Apps analogue). Sets a distinct OTel service name so this process is traced
and audited independently, opens the run's root span, wires each agent's identity, runs the
Agent Framework workflow, and reports the approval request to act on.

Two entry points share `run_once()`:
  CLI / one-shot job:  .venv/bin/python -m lab.workloads.visio_to_archimate.host [diagram] [-r docs...]
                       (or VISIO_DIAGRAM / VISIO_REQUIREMENTS env for a cloud job)
  long-lived host:     src/lab/workloads/visio_to_archimate/consumer.py — runs `run_once` per
                       workflow:requests event (what the review app's Submit page publishes)

Composition: each entry point builds the process container ONCE (`lab.platform.container.build(SERVICE)`
— config, the pooled Redis client, the tracer named after SERVICE) and hands it down as `root`; nothing
below constructs a client. Inputs are paths (local dev) or art:// refs — refs are read ONLY through the
gateway's storage-mcp tools, so this process holds no object-store credentials. All egress is governed
by the gateway; the ADOIT write is staged for human approval (review app / Telegram / CLI).
"""
import asyncio
import os
import sys
from pathlib import Path

from opentelemetry import propagate, trace

from lab.platform import config, container, otel, runlog
from lab.platform.contracts import ArtifactRef
from lab.workloads.identity import agent_headers
from lab.workloads.visio_to_archimate.workflow import make_cfg, run_workflow

HERE = Path(__file__).resolve().parent
SERVICE = "process-visio-to-archimate"   # one distinct service name per business process (docx §7)
DEFAULT_VSDX = config.VAR_DIR / "inputs" / "visio_to_archimate" / "lab-system.vsdx"   # generated by make_sample_vsdx


def _cred(prefix: str) -> str:
    """The agent's bearer credential (Entra JWT via MSAL, or its durable virtual key)."""
    return agent_headers(prefix)["Authorization"].removeprefix("Bearer ").strip()


async def run_once(root, diagram: str, requirements: list[str] | None = None, on_trace=None) -> dict:
    """One governed run: root span -> agent identities -> workflow -> approval request.
    `root` is the process container (tracer + Redis come from it). Returns the workflow output plus
    `trace_id`. `on_trace(trace_id)` fires as soon as the span exists so a caller (the consumer) can
    publish it before the run finishes."""
    requirements = list(requirements or [])
    tr, r = root.tracer(), root.redis()
    with tr.start_as_current_span("visio-to-archimate-run") as span:
        trace_id = format(span.get_span_context().trace_id, "032x")
        span.set_attribute("lab.trace_id", trace_id)
        span.set_attribute("visio.input", os.path.basename(diagram))
        span.set_attribute("visio.requirements", len(requirements))
        if on_trace:
            on_trace(trace_id)
        traceparent: dict = {}
        propagate.inject(traceparent)      # W3C headers for this run -> gateway + MCP join the trace
        root_ctx = trace.set_span_in_context(span)
        # live run visibility (review app -> Runs): one run-log per run, keyed by its trace id
        run_id = trace_id
        runlog.start(run_id, input=os.path.basename(diagram), trace_id=trace_id, client=r)

        # ONE config builder for every host (see workflow.make_cfg) — no per-host drift (review A-F12)
        cfg = make_cfg(ba_cred=_cred("BA_AGENT"), ar_cred=_cred("ARCHITECT_AGENT"),
                       traceparent=traceparent, schema=_load_schema(), tracer=tr, root_ctx=root_ctx,
                       mcp_url=root.config.gateway_mcp_url(), run_id=run_id)
        try:
            out = await run_workflow(cfg, {"diagram": diagram, "requirements": requirements})
        except Exception as e:
            runlog.finish(run_id, "failed", error=f"{type(e).__name__}: {str(e)[:300]}", client=r)
            raise
        runlog.finish(run_id, "done", approval_id=out.get("request_id"),
                      xml_ref=out.get("xml_ref"), xlsx_ref=out.get("xlsx_ref"), client=r)
    return {**out, "trace_id": trace_id}


async def main(root, diagram: str, requirements: list[str] | None = None):
    print(f"input:    {diagram}")
    for req in requirements or []:
        print(f"requires: {req}")
    out = await run_once(root, diagram, requirements, on_trace=lambda t: print(f"trace id: {t}"))
    _shutdown()
    print("\n=== result ===")
    print(f"model elements/relations: {out['summary']['elements']}/{out['summary']['relations']}  "
          f"views: {out['summary']['views']}  semantic warnings: {out['summary']['semantic_warnings']}")
    print(f"artifacts: {out['xml_ref']}  (+{len(out['svg_refs'])} svg refs)")
    print(f"approval requested: {out['request_id']} -> {out['status']}")
    print(f"review at: {out.get('review_app')}   (./lab.sh review)")
    print(f"trace:     {root.config.jaeger_ui_url()}  (id {out['trace_id']})")


def _load_schema():
    import json
    return json.loads((HERE / "schemas" / "ba_output.schema.json").read_text())


_shutdown = otel.shutdown   # flush the exporter before a one-shot run exits


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Visio/diagram (+ requirements) -> ArchiMate, staged for approval")
    ap.add_argument("diagram", nargs="?", default=str(DEFAULT_VSDX),
                    help="the system diagram: a .vsdx OR an image (.png/.jpg/...), as a path or an art:// ref")
    ap.add_argument("-r", "--requirements", nargs="*", default=[],
                    help="requirements documents (.docx/.pdf/.md/.txt), paths or art:// refs "
                         "(upload: python -m lab.substrate.review.uploads upload <files>)")
    a = ap.parse_args()
    # A cloud job has no CLI: VISIO_DIAGRAM / VISIO_REQUIREMENTS (space-separated) env vars — set
    # as `# CLOUD:` lines in .env, typically art:// refs from `inputs upload` — override the
    # defaults, so the same container runs real uploaded inputs instead of the generated fixture.
    if len(sys.argv) == 1:
        a.diagram = os.environ.get("VISIO_DIAGRAM") or a.diagram
        a.requirements = os.environ.get("VISIO_REQUIREMENTS", "").split() or a.requirements
    for src in [a.diagram, *a.requirements]:
        # a `#<page>` fragment selects one page of a multi-page .vsdx — strip it for the existence check
        if not ArtifactRef.is_ref(src) and not os.path.exists(src.partition("#")[0]):
            sys.exit(f"no such file: {src}")
    asyncio.run(main(container.build(SERVICE), a.diagram, a.requirements))   # the composition root
