"""Host process for the Visio->ArchiMate workflow — one Python host per business process
(the Azure Container Apps analogue). Sets a distinct OTel service name so this process is traced
and audited independently, opens the run's root span, wires each agent's identity, runs the
Agent Framework workflow, and reports the approval request to act on.

Two entry points share `run_once()`:
  CLI / one-shot job:  .venv/bin/python -m lab.workloads.visio_to_archimate.host [diagram] [-r docs...]
                       (or VISIO_DIAGRAM / VISIO_REQUIREMENTS env for a cloud job)
  long-lived host:     src/lab/workloads/visio_to_archimate/consumer.py — runs `run_once` per
                       workflow:requests event (what the review app's Submit page publishes)

Composition: each entry point builds the process container ONCE (`lab.platform.container.build(SERVICE)`
— config, the pooled Redis client, the tracer named after SERVICE) and hands it down as `root`; nothing
below constructs a client. Inputs are paths (local dev) or art:// refs — refs are read ONLY through the
gateway's storage-mcp tools, so this process holds no object-store credentials. All egress is governed
by the gateway; the EA-repository write is staged for human approval (review app / Teams / Telegram / CLI).
"""
import asyncio
import os
import sys
from pathlib import Path

from lab.platform import config, container, otel
from lab.platform.contracts import VISIO_TO_ARCHIMATE, ArtifactRef
from lab.workloads.identity import agent_headers
from lab.workloads.run import governed_run
from lab.workloads.visio_to_archimate.workflow import make_cfg, run_workflow

HERE = Path(__file__).resolve().parent
SERVICE = "process-visio-to-archimate"   # one distinct service name per business process (docx §7)
PROCESS = VISIO_TO_ARCHIMATE.name        # the registry names the process; nothing re-types it
DEFAULT_VSDX = config.VAR_DIR / "inputs" / "visio_to_archimate" / "lab-system.vsdx"   # generated by make_sample_vsdx


def _cred(prefix: str) -> str:
    """The agent's bearer credential (Entra JWT via MSAL, or its durable virtual key)."""
    return agent_headers(prefix)["Authorization"].removeprefix("Bearer ").strip()


def run_fields(out: dict) -> dict:
    """The run-log fields a finished run's board row carries: the references a reviewer follows from
    the Runs board to what the run produced (its approval request and its artifacts). ONE mapping
    for every host — the CLI/consumer below, and DevUI via `devui_entry.instrument_runs` — so a row
    means the same thing whoever started the run. `None` values are dropped by `runlog.finish`."""
    return {"approval_id": out.get("request_id"), "xml_ref": out.get("xml_ref")}


async def run_once(root, diagram: str, requirements: list[str] | None = None, on_trace=None) -> dict:
    """One governed run: root span -> agent identities -> workflow -> approval request.

    The span, the trace headers, the run-log entry and the one way a run is closed are the SHARED
    skeleton (`lab.workloads.run.governed_run`); `make_cfg` is the ONE config builder every host of
    this process uses (review A-F12), so neither half drifts per host.
    """
    requirements = list(requirements or [])
    return await governed_run(
        root, span_name="visio-to-archimate-run", process=PROCESS,
        label=os.path.basename(diagram), on_trace=on_trace,
        attrs={"visio.input": os.path.basename(diagram), "visio.requirements": len(requirements)},
        cfg=lambda c: make_cfg(ba_cred=_cred("BA_AGENT"), ar_cred=_cred("ARCHITECT_AGENT"),
                               traceparent=c.traceparent, schema=_load_schema(), tracer=c.tracer,
                               root_ctx=c.root_ctx, mcp_url=c.mcp_url, run_id=c.run_id),
        run=run_workflow, inputs={"diagram": diagram, "requirements": requirements},
        fields=run_fields)


async def main(root, diagram: str, requirements: list[str] | None = None):
    print(f"input:    {diagram}")
    for req in requirements or []:
        print(f"requires: {req}")
    out = await run_once(root, diagram, requirements, on_trace=lambda t: print(f"trace id: {t}"))
    _shutdown()
    print("\n=== result ===")
    print(f"model elements/relations: {out['summary']['elements']}/{out['summary']['relations']}  "
          f"views: {out['summary']['views']}  semantic warnings: {out['summary']['semantic_warnings']}")
    print(f"artifacts: {out['xml_ref']}  (+{len(out['svg_refs'])} svg refs)")
    print(f"approval requested: {out['request_id']} -> {out['status']}")
    print(f"review at: {out.get('review_app')}   (./lab.sh review)")
    print(f"trace:     {root.config.jaeger_ui_url()}  (id {out['trace_id']})")


def _load_schema():
    import json
    return json.loads((HERE / "schemas" / "ba_output.schema.json").read_text())


_shutdown = otel.shutdown   # flush the exporter before a one-shot run exits


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Visio/diagram (+ requirements) -> ArchiMate, staged for approval")
    ap.add_argument("diagram", nargs="?", default=str(DEFAULT_VSDX),
                    help="the system diagram: a .vsdx OR an image (.png/.jpg/...), as a path or an art:// ref")
    ap.add_argument("-r", "--requirements", nargs="*", default=[],
                    help="requirements documents (.docx/.pdf/.md/.txt), paths or art:// refs "
                         "(upload: python -m lab.substrate.review.uploads upload <files>)")
    a = ap.parse_args()
    # A cloud job has no CLI: VISIO_DIAGRAM / VISIO_REQUIREMENTS (space-separated) env vars — set
    # as `# CLOUD:` lines in .env, typically art:// refs from `inputs upload` — override the
    # defaults, so the same container runs real uploaded inputs instead of the generated fixture.
    if len(sys.argv) == 1:
        a.diagram = os.environ.get("VISIO_DIAGRAM") or a.diagram
        a.requirements = os.environ.get("VISIO_REQUIREMENTS", "").split() or a.requirements
    for src in [a.diagram, *a.requirements]:
        # a `#<page>` fragment selects one page of a multi-page .vsdx — strip it for the existence check
        if not ArtifactRef.is_ref(src) and not os.path.exists(src.partition("#")[0]):
            sys.exit(f"no such file: {src}")
    asyncio.run(main(container.build(SERVICE), a.diagram, a.requirements))   # the composition root
